version: "3.9"

services:
  #mongodb
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-db:/data/db

    container_name: mongodb

  #client
  frontend:
    build:
      context: "./client"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend

    container_name: react-app

  #api
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGO_URL = ${MONGO_URL}
      - JWT_SECRET = ${JWT_SECRET}
    depends_on:
      - mongodb

    container_name: node-api

volumes:
  mongo-db: {}
